### ISSUE TITLE
Does implementing vue-analytics automatically add basic tracking?

### ISSUE THREAD

**Issue by awitherow** [ScreamZ/vue-analytics#15]
@ScreamZ Does this add basic tracking to the site or do I need to copy and paste the normal script in from Google?

I am just assuming it does because we pass in the router info already... but figured I would ask.

**Comment by ScreamZ** [comment]
Hey, thanks for the feedback.

If you're passing the router you've automated tracking based on route name, you can override it using a meta.

Check readme for more information.

Best regards

**Comment by awitherow** [comment]
Sick. Thanks!
