### ISSUE TITLE
Path of the active page is always '/' if router mode is 'hash' ?

### ISSUE THREAD

**Issue by ALPIXELMaiki** [ScreamZ/vue-analytics#18]
Hi,

First, thanks for you plugin :)

When browse my Vuejs App, and checking my GG analytics real time dashboard on a second panel, the active path  is always '/', even if my app real path is '/#/my-page'

My vue-router configuration mode is set to 'hash'. 
Is it the issue ?

Best regards,

**Comment by ALPIXELMaiki** [comment]
Seems the problem comes from my app urls with 'hash' mode from router :
"domain.com/#/page" => seems vue-ua track only "domain.com/" path and don't go after the # symbol

**Comment by ScreamZ** [comment]
Hey, thanks for the feedback! Appreciated !

Yep that's a classic behavior I think, in production shouldn't you use hash mode ?

Will take a look further to check if I can do something for your case.

Regards

**Comment by ALPIXELMaiki** [comment]
Hi ScreamZ,

Thanks for your answer :)
In production, i'll use the 'history' mode. I could tell you if the problem is the same in production or not :)

Regards

**Comment by ScreamZ** [comment]
@ALPIXELMaiki Any news ?

**Comment by ALPIXELMaiki** [comment]
Hey @ScreamZ 

Not for the moment. My App is a verr big one, and will be put in production on few months.
You can close this issue, nad i will come back to you if the problem came back :)

Thanks !
