### ISSUE TITLE
Support for timings

### ISSUE THREAD

**Issue by ScreamZ** [ScreamZ/vue-analytics#2]
Add support for analytics timing tracking https://developers.google.com/analytics/devguides/collection/analyticsjs/user-timings

**Comment by paveldk** [comment]
+1

**Comment by ScreamZ** [comment]
@paveldk I'll work on it

**Comment by reverland** [comment]
Any progress on this?

**Comment by ScreamZ** [comment]
@reverland Will try to implement this between 12-14 hour one day in the week

**Comment by reverland** [comment]
@ScreamZ cool~

**Comment by ScreamZ** [comment]
@reverland @paveldk 

Just released v1.3.0 https://github.com/ScreamZ/vue-analytics/releases/tag/v1.3.0

Support for timings.

Feel free to feedback on that and close issue.

Best regards
