### ISSUE TITLE
Question on SPA at a segment

### ISSUE THREAD

**Issue by jesseschutt** [ScreamZ/vue-analytics#20]
Hello! Thanks for your work on this plugin 👍🏼

I was wondering if you could help me with a question on usage in my app. I have a Vue + Vue Router app that is loaded at https://example.com/dashboard#/. When I use vue-analytics to automatically pass data to Google Analytics, the only page that exists in Google Analytics is `/dashboard`.

<img width="126" alt="screenshot 2017-05-17 11 48 23" src="https://cloud.githubusercontent.com/assets/353047/26165763/c2b8af1a-3af6-11e7-8638-65e8bbd9f607.png">

Should I be seeing different pages in my GA reporting? And if so, do you have any advice on what I might be doing wrong?

Thank you!

**Comment by ScreamZ** [comment]
Hi,
thanks.

It's been a while I haven't create a new project with my own lib :p

Do you have some event that are dispatched in the console log ? (You should enable debug mode ?)

**Comment by jesseschutt** [comment]
Hey, thanks for answering so fast :-)

Yes, the events are dispatching like this:

<img width="525" alt="screenshot 2017-05-17 12 08 56" src="https://cloud.githubusercontent.com/assets/353047/26166621/afbd0a7a-3af9-11e7-8f55-5b82695d5c5a.png">

**Comment by ScreamZ** [comment]
Can you try adding a "mobile" view instead of we view in analytics (by creating another ID).

**Comment by daniel-keller** [comment]
I think I'm having a similar issue. I'm manually triggering page views with `this.$ua.trackView('myPageName')` as well as events with `this.$ua.trackEvent`. I see the proper debug information in the console log but in Google Analytics only ever see the landing page.

![untitled](https://user-images.githubusercontent.com/4036797/27050779-ba728160-4f81-11e7-8bc4-acc2d9884871.png)

![untitled](https://user-images.githubusercontent.com/4036797/27050707-9050e5ac-4f81-11e7-96bb-0b705d73f12e.png)

**Comment by daniel-keller** [comment]
After looking at the [google analytics documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/command-queue-reference) I was unable to find the fields `screenName` or the hit type `screenview`. I suspect google has deprecated these terms. 
```
// From AnalyticsPlugin.js
ga('set', 'screenName', screenName)
ga('send', 'screenview')
```
In my own code I was able to generate page views with the following
```
// From AnalyticsPlugin.js
ga('set', 'page', screenName)                    
ga('send', 'pageview')
```
The requirements for event hit type parameters seem to have changed as well.

**Comment by ScreamZ** [comment]
I think this is because Screen is only for mobile apps in GA. I just saw this, i'm working on some kind of bridge that allows it working in classic GA vue.

You're sure using Google tag assistant that the event is truly dispatched ?

**Comment by daniel-keller** [comment]
I have confirmed with Google Tag Assistant that the event is properly dispatched when I use `page` and `pageview` in my own code.
