### ISSUE TITLE
Failing to load minified js

### ISSUE THREAD

**Issue by aschalund** [ScreamZ/vue-analytics#23]
Having a weird issue with loading this into my project. 

`Uncaught TypeError: n.afterEach is not a function
    at d (vue-analytics.min.js?394b:1)`

I am including the plugin as directed in the readme but when i run my main application it crashes on the above error.  

Hope you can help. Let me know what else you would like to see.

**Comment by ScreamZ** [comment]
It depends on the instance of vueRouter you are passing to the config 

Are you passing a true vue-router ?

**Comment by aschalund** [comment]
I was able to resolve this with a change to my router call.
